/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iestr.jmff.t1_p1.vista;

import iestr.jmff.t1_p1.controlador.TablapapeleriaJpaController;
import iestr.jmff.t1_p1.modelo.Tablapapeleria;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * <p><strong>Clase Menu</strong></p>
 * <p>Extiende javax.swing.JFrame</p>
 * 
 * <p>Ventana principal contenedora de todos
 * los botones con sus respectivas funciones.</p>
 * 
 * @author Fuentes
 */
public class Menu extends javax.swing.JFrame {
    private static List<Tablapapeleria> productos;
    private static TablapapeleriaJpaController producto;
    
    /**
     * <p>Constructor de la clase Menu: configura
     * la ventana y crea una instancia de 
     * TablaPapeleriaJpaController.</p>
     * 
     * @author Fuentes
     */
    public Menu() {
        //Nombre y configuración
        setTitle("Menu inicio");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(this);
               
        //Color de fondo
        Color color = new Color(200,200,250);
        this.getContentPane().setBackground(color);
        
        //Base de datos
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");
        producto = new TablapapeleriaJpaController(emf);
        productos = producto.findTablapapeleriaEntities();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 200, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(200, 200, 250));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btn1.setText("Nuevo Producto");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modify.png"))); // NOI18N
        btn2.setText("Modificar Producto");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Line Chart.png"))); // NOI18N
        btn3.setText("Listar Productos");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        btn4.setText("Buscar Producto");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btn5.setText("Eliminar Producto");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn1)
                .addGap(18, 18, 18)
                .addComponent(btn2)
                .addGap(18, 18, 18)
                .addComponent(btn3)
                .addGap(18, 18, 18)
                .addComponent(btn4)
                .addGap(18, 18, 18)
                .addComponent(btn5)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * <p>Abre la ventana <a href="NuevoProducto.java">NuevoProducto.java</a>
     * , configurando su cierre respecto a <a href="Menu.java">Menu.java</a></p>
     * 
     * @author Fuentes
     * @param evt
     */
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        NuevoProducto n = new NuevoProducto();
        n.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        n.setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * <p>Abre la ventana <a href="ListarProductos.java">ListarProductos.java</a>
     * , configurando su cierre respecto a <a href="Menu.java">Menu.java</a></p>
     * 
     * @author Fuentes
     * @param evt
     */
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        ListarProductos n = new ListarProductos();
        n.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        n.setVisible(true);
    }//GEN-LAST:event_btn3ActionPerformed

    /**
     * <p>Abre la ventana <a href="ModificarProducto.java">ModificarProducto.java</a>
     * , configurando su cierre respecto a <a href="Menu.java">Menu.java</a></p>
     * 
     * @author Fuentes
     * @param evt
     */
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        ModificarProducto n = new ModificarProducto();
        n.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        n.setVisible(true);
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * <p>Abre la ventana <a href="EliminarProducto.java">EliminarProducto.java</a>
     * , configurando su cierre respecto a <a href="Menu.java">Menu.java</a></p>
     * 
     * @author Fuentes
     * @param evt
     */
    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        EliminarProducto n = new EliminarProducto();
        n.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        n.setVisible(true);
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * <p>Abre la ventana <a href="BuscarProducto.java">BuscarProducto.java</a>
     * , configurando su cierre respecto a <a href="Menu.java">Menu.java</a></p>
     * 
     * @author Fuentes
     * @param evt
     */
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        BuscarProducto n = new BuscarProducto();
        n.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        n.setVisible(true);
    }//GEN-LAST:event_btn4ActionPerformed

    /**
     * <p>Recibe un String, el cual se mostrará en un 
     * <a href="javax.swing.JOptionPane.java">JOptionPane.java</a>,
     * de tipo INFORMATION_MESSAGE con el Titulo "COMPLETADO".</p>
     * 
     * @author Fuentes
     * @param texto 
     */
    static void exito(String texto){
        JOptionPane mensaje = new JOptionPane();
        JOptionPane.showMessageDialog(mensaje,texto,"COMPLETADO",JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * <p>Recibe un String, el cual se mostrará en un 
     * <a href="javax.swing.JOptionPane.java">JOptionPane.java</a>,
     * de tipo ERROR_MESSAGE con el Titulo "ERROR".</p>
     * 
     * @author Fuentes
     * @param texto 
     */
    static void error(String texto){
        JOptionPane mensaje = new JOptionPane();
        JOptionPane.showMessageDialog(mensaje,texto,"ERROR",JOptionPane.ERROR_MESSAGE);
    }
    
    
    /**
     * <p>Recibe un String, el cual será analizado
     * para comprobar si es un Double de máximo 2
     * decimales.</p>
     * 
     * @author Fuentes
     * @param texto 
     * @return boolean True si es Double / False si no es Double
     */
    static boolean esDouble(String texto){
        int cantidadPuntos = 0;
        for(int i = 0 ; i < texto.length() ; i++){
            if(Character.isDigit(texto.charAt(i))){
                
            }else{
                if(texto.charAt(i)=='.'){
                    cantidadPuntos++;
                    if(cantidadPuntos>1) return false;
                    if(i!=texto.length()-3) return false;
                }else{
                    return false;
                }
            }
        }
        return true;
    }
    
    /**
     * <p>Recibe un código, el cual será comparado
     * para ver si hay algún producto con ese mismo
     * código.</p>
     * 
     * @author Fuentes
     * @param codigo 
     * @return boolean <b>True</b> si está libre (no existe) / <b>False</b> si no está libre (existe)
     */
    static boolean codigoLibre(String codigo){
        if((productos==null) || (!productos.isEmpty())){
            for(Tablapapeleria p : productos){
                if(p.getCodigo().equals(codigo)){
                    return false;
                }
            }
        }
        return true;
    }
    
    /**
     *<p>Invoca el método run del Menu, creando una instancia
     * y poniéndolo visible.</p>
     * 
     * @author JFrame
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    // End of variables declaration//GEN-END:variables
}
